### PR TITLE
Don't try to escape double quotes if none present

### PR DESCRIPTION
**Pull request by basilisk487**

### CODE REVIEW

**Comment by panghy** [comment]
Why is this change necessary?

**Comment by basilisk487** [comment]
As it turned out, on loads that use point tags, escapeQuotes uses more CPU than pointToStringSB itself (see jvmtop output below) - and it's only useful in fringe cases. So, this was a "low hanging fruit" opportunity to further reduce CPU usage. 

```
  15.53% (    30.63s) org.antlr.v4.runtime.atn.LexerATNSimulator.execATN()
  10.67% (    21.04s) com.wavefront.agent.PostPushDataTimedTask.addPoint()
   8.76% (    17.28s) org.antlr.v4.runtime.BufferedTokenStream.getText()
   7.57% (    14.92s) com.wavefront.ingester.IngesterFormatter.getLiteral()
   6.35% (    12.53s) com.wavefront.agent.PointHandlerImpl.escapeQuotes()
   5.21% (    10.28s) com.wavefront.ingester.IngesterFormatter.parseValue()
   5.20% (    10.25s) com.wavefront.agent.PointHandlerImpl.pointToStringSB()
```

**Comment by panghy** [comment]
I don't think doing something O(N) twice going to be faster than what StringUtils is already doing (it has an indexOf() optimization which is what contains() would have done).

I think jvmtop is misleading in getting accurate traces (that's the woe of doing sampling), try yourkit tracing if we want to look deeper into what's really going on.

**Comment by basilisk487** [comment]
Agreed - the CPU profile does appear misleading, as StringUtils already performs that check. Closing PR.

**Pull request closed without merging**
